language: node_js
node_js:
  - 0.10
before_install:
  - npm install phantomjs --save-dev
  - git clone https://github.com/ecomfe/saber-lang.git test/dep/saber-lang/0.3.1
  - git clone https://github.com/ecomfe/saber-tap.git test/dep/saber-tap/0.1.2
install: true
